Que 335 elm formatted text fails parsing bold
NoRedInk/elm-formatted-text pull request #10
Opened 2022-10-12 19:31 UTC by luizcarlos1405

Fixes https://linear.app/noredink/issue/QUE-335/elm-formatted-text-fails-parsing-bold-sometimes.

2022-10-15 02:02 UTC, juanedi commented
Hello there! Sorry, I didn't get to review this today and I'll be OOO on Monday. Feel free to request another reviewer if you'd rather have this merged soon.

2022-10-17 09:22 UTC, stoeffel commented on src/FormattedText.elm
> +        |> split "\n\r"
We should use `String.lines` which breaks on any linebreak characters https://github.com/elm/core/blob/8e99db3fcbb101838c36d534a7be7add6b6d739e/src/Elm/Kernel/String.js#L177
Additionally, we should mention changes like this in the changelog.

2022-10-17 09:24 UTC, stoeffel commented on src/FormattedText.elm
> +        |> split "\n\r"
oh nevermind this uses split on a formatted text.

2022-10-17 09:24 UTC, stoeffel commented on src/FormattedText.elm
> +        |> split "\n\r"
how about we do it with the regex like for `words`? that seems a little more performant.

2022-10-17 09:27 UTC, stoeffel requested changes
Looks good. I only have one change request. Thanks for porting the tests!

2022-10-17 09:50 UTC, stoeffel approved these changes
Addressed my own comments.

2022-10-17 09:59 UTC, merged